name: 'Code build validation'

on:
  push:
    branches: [main, develop]

jobs:
  Format:
    name: Format code and run eslint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test --if-present
